name: GitHub Actions Version Updater

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.1
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}